# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71bbb7147f21653adc6bb5005bf6fbd80b8b9839f395e42a512dbe74dd4833927fb2987d55ac689a1074000d71f6390744e6a2160438e79fa9a37fb246c9dddf

test:
  secret_key_base: 0d27ebebc170d0973a463377ffa0457adce1521528845d0e5421a1acb65c064b19781b72fbcad341c9e2ccdf101ac11f6a8ecfb3c8a0baefe67796246be89ba0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
